--- #YAML:1.0
name:                WWW-Romeo
version:             0.21.01
abstract:            Where for art thou?
license:             ~
author:              
    - Mikey G <mikeyg@cc-wc.wayne.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
